### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by danymat** [esquires/neorg-gtd-project-tags#1]
Hello @esquires, we just agreed on a naming convention for Neorg.
Could it be possible to rename the extension by taking into account this convention?

Link to it: https://github.com/nvim-neorg/neorg/wiki#modules-naming-convention

**Comment by esquires** [comment]
No problem. The update is on master in eb97cc0.

**Comment by danymat** [comment]
Updated https://github.com/nvim-neorg/neorg/tree/rewrite-readme#external-modules with the new name
