### ISSUE TITLE
Error `neorg.modules.base not found` After Configured

### ISSUE THREAD

**Issue by ldmax** [esquires/neorg-gtd-project-tags#4]
![image](https://github.com/esquires/neorg-gtd-project-tags/assets/4306230/c5c4eef8-4973-40ab-8743-b5236d7189cb)
Hi esquires, thanks for creating this plugin!

I'm using Neorg version 6.2.0, below is my configuration:
```lua
return {
  {
    "nvim-neorg/neorg",
    tag = "v6.2.0",
    pin = true,
    run = ":Neorg sysnc-parsers",
    config = function()
      require("neorg").setup({
        load = {
          ["external.gtd-project-tags"] = {},
          ["core.defaults"] = {},
          ["core.concealer"] = {},
          ["core.ui.calendar"] = {},
          ["core.dirman"] = {
            config = {
              workspaces = {
                default = "$HOME/norg",
                work = "$HOME/norg/work",
                home = "$HOME/norg/home",
                plan = "$HOME/norg/plan",
                trading = "$HOME/norg/trading",
                journal = "$HOME/norg/journal",
                org = "$HOME/org-roam",
                nvim = "$HOME/norg/nvim",
              },
              default_workspace = "default",
            },
          },
        },
      })
    end,
  },
}
```
And this is my configuration for your plugin:
```lua
return {
  "esquires/neorg-gtd-project-tags",
}
```

May I ask for some advice why I got the error shown in screenshot please? Thanks in advance!

**Comment by esquires** [comment]
Thanks for the question. neorg dropped gtd as part of a big rewrite. I think gtd is coming back in the next few months though:

https://github.com/nvim-neorg/neorg/issues/695

https://github.com/nvim-neorg/neorg/discussions/1110

Unfortunately that means this repo can't work anymore. I'll add a note to the readme and archive it.
